version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app-test
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - test_network

  db:
    image: postgres:latest
    container_name: db-test
    environment:
      POSTGRES_USER: ${DEFAULT_USER}
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD}
      POSTGRES_DB: ${DEFAULT_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network:
    driver: bridge
